---
- name: Install passlib library
  hosts: 159.203.31.138
  become: yes
  connection: local
  remote_user: root
  tasks:
    - name: Install passlib
      package:
        name: python3-passlib
        state: present

- name: Set up user and add user to sudo and docker groups
  hosts: 159.203.31.138
  connection: local
  remote_user: root
  become: true
  tasks:
    - name: Set up a new user
      user:
        name: ieeeadmin
        state: present
        createhome: yes

    - name: Add user to sudo group
      user:
        name: ieeeadmin
        groups: sudo
        append: yes

    - name: Add user to docker group
      user:
        name: ieeeadmin
        groups: docker
        append: yes

- name: Generate password and assign it to the user
  hosts: 159.203.31.138
  connection: local
  remote_user: root
  tasks:
    - name: Generate a random password
      set_fact:
        random_password: "{{ lookup('password', '/dev/null chars=ascii_letters,digits,punctuation length=32') }}"

- name: Assign password
  hosts: 159.203.31.138
  become: yes
  gather_facts: no
  connection: local
  remote_user: root
  tasks:
    - name: Assign password to new user
      user:
        name: ieeeadmin
        password: "{{ random_password | password_hash('sha512') }}"


